# Generated by Django 2.1 on 2018-08-17 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_hash', models.CharField(max_length=128)),
                ('result', models.CharField(max_length=32)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.Website')),
            ],
        ),
    ]
