# Generated by Django 2.1 on 2018-08-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0002_check_website_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='check',
            options={'get_latest_by': 'timestamp'},
        ),
        migrations.AlterField(
            model_name='check',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
