# Generated by Django 2.1.2 on 2018-10-09 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0003_auto_20180818_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='check',
            options={'get_latest_by': 'timestamp', 'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='check',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='websites.Website'),
        ),
    ]
