# Generated by Django 2.1.2 on 2018-10-09 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_auto_20181009_0943'),
        ('watcher', '0004_auto_20181009_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_hash', models.CharField(max_length=128)),
                ('result', models.CharField(blank=True, choices=[('OK', 'Ok'), ('ALERT', 'Alert'), ('ERROR', 'Error'), (None, 'None')], default=None, max_length=128)),
                ('error', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('website_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_checks', to='websites.WebsiteCheckSettings')),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
    ]
