# Generated by Django 2.1.2 on 2018-10-09 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0005_websitecheck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websitecheck',
            old_name='website_hash',
            new_name='check_hash',
        ),
    ]
