# Generated by Django 2.1.2 on 2018-10-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0006_auto_20181009_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecheck',
            name='error',
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
    ]
