# Generated by Django 2.1.2 on 2018-10-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0009_auto_20181019_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitechecksettings',
            name='website_hash',
            field=models.URLField(blank=True),
        ),
    ]
