# Generated by Django 2.1.2 on 2018-10-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0011_auto_20181026_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecheck',
            name='error',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
