# Generated by Django 2.1.2 on 2018-10-09 09:43

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_websitechecksettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitechecksettings',
            name='dom_exclusions',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
