# Generated by Django 2.1.2 on 2018-10-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0009_auto_20181019_1030'),
        ('websites', '0004_auto_20181009_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitechecksettings',
            name='dom_exclusions',
        ),
        migrations.RemoveField(
            model_name='websitechecksettings',
            name='website',
        ),
        migrations.DeleteModel(
            name='WebsiteCheckSettings',
        ),
    ]
